### ISSUE TITLE
Codificación incorrecta de texto en destino

### ISSUE THREAD

**Issue by nukeador** [DaviidMM/api-auvasa#1]
Hola y gracias por el trabajo del API, lo estoy intentando usar para un proyecto personal para hacer seguimiento de tiempos de mis paradas y buses habituales :-)

El json devuelve codificación incorrecta para caracteres unicode.

https://api-auvasa.vercel.app/999/1

```
[
  {
    "destino": "B. ESPA�A",
    "linea": "1",
    "tiempoRestante": 8
  }
]
```

**Comment by DaviidMM** [comment]
Buenas! Parece ser que la web de auvasa utiliza la codificación Windows-1252 y había conflicto con el script. Se soluciona el problema en el commit 3ff918986ec6067bf8510eb041bba9d60b8c5f8c .
