### ISSUE TITLE
Lineas con +30 minutos de espera

### ISSUE THREAD

**Issue by nukeador** [DaviidMM/api-auvasa#2]
Actualmente el API devuelve 30 para lineas que tienen +30 minutos de espera.

Ejemplo:

https://api-auvasa.vercel.app/999/18

```
[
  {
    "destino": "CISTERNIGA",
    "linea": "18",
    "tiempoRestante": 30
  }
]
```

En la web de auvasa

![image](https://github.com/DaviidMM/api-auvasa/assets/531906/cd1baeea-3638-48ae-a5e0-d70cd7e06056)

**Comment by DaviidMM** [comment]
El script obtiene su información desde la web de Auvasa, en la cual solo se muestra información hasta `+30` minutos, no se detalla más.

Se puede utilizar otro valor para definir aquellos buses que vayan a tardar más de 30 minutos, por ejemplo `999`, pero tal y como es la web de Auvasa actual, no se puede saber con exactitud el tiempo estimado.

**Comment by nukeador** [comment]
Cierto, pero que al menos el api devuelve 30+ en vez de 30, para poder mostrar que no es que queden 30 minutos, si no que quedan más de 30.

**Comment by DaviidMM** [comment]
En el commit 545a96ebe661004f09d1902d5db6179be9d20db5 se añade una nueva propiedad, `esExacto`. Esta propiedad indica si el tiempo del campoo `tiempoRestante` es exacto o, por el contrario, está referenciado con un `+` en la web de Auvasa (no exacto).
