### ISSUE TITLE
Nombre y número de parada

### ISSUE THREAD

**Issue by nukeador** [DaviidMM/api-auvasa#4]
Sería genial que el API devolviera el número y el nombre de la parada también para poderlo reutilizar.

nombreParada: Plaza Cruz Verde 5
numeroParada: 811

**Comment by DaviidMM** [comment]
Solucionado en el commit 96602ac93ca28b16f9441b6f9a1e6f41ad151479.

Se ha añadido información de la parada bajo la propiedad `parada` del resultado devuelvo. Ahora la información de los buses se devuelve bajo la propiedad `buses`.
